version: "3"
services:
  application:
    user: node
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 14
    command: sleep infinity
    env_file: .env.development
    ports:
      - 1313:1313
    volumes:
      - ..:/workspace
    links:
      - database

  database:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file: .env.development
